common: add support for export for NOOBS/OSIRIS

diff --git a/common b/common
--- a/common
+++ b/common
@@ -124,6 +124,90 @@ EOF
   sudo mount $ROOT_DEV rootfs
   sudo cp rootfs/etc/rpi-issue boot/issue.txt
   [ -n "$RASPBIAN" ] && sudo mv rootfs/etc/ld.so.preload.disable rootfs/etc/ld.so.preload
+  if [ -n "$NOOBS" ]; then
+    mkdir -p ../noobs
+    sudo tar -C boot -czf ../noobs/boot.tar.gz --preserve .
+    sudo tar -C rootfs -czf ../noobs/root.tar.gz --preserve .
+    cat <<\EOF > ../noobs/partition_setup.sh
+#!/bin/sh
+
+set -ex
+
+if [ -z "$part1" ] || [ -z "$part2"]; then
+  printf "Error: missing environment variable part1 or part2\n" 1>&2
+  exit 1
+fi
+
+mkdir -p /tmp/1 /tmp/2
+
+mount "$part1" /tmp/1
+mount "$part2" /tmp/2
+
+sed /tmp/1/cmdline.txt -i -e "s|root=/dev/[^ ]*|root=${part2}|"
+sed /tmp/2/etc/fstab -i -e "s|^.* / |${part2}  / |"
+sed /tmp/2/etc/fstab -i -e "s|^.* /boot |${part1}  /boot |"
+
+umount /tmp/1
+umount /tmp/2
+EOF
+    cat <<\EOF > ../noobs/partitions.json
+{
+  "partitions": [
+    {
+      "label": "boot",
+      "filesystem_type": "FAT",
+      "partition_size_nominal": 60,
+      "want_maximised": false,
+      "uncompressed_tarball_size": 19
+    },
+    {
+      "label": "root",
+      "filesystem_type": "ext4",
+      "partition_size_nominal": 1790,
+      "want_maximised": true,
+      "mkfs_options": "-O ^huge_file",
+      "uncompressed_tarball_size": 1400
+    }
+  ]
+}
+EOF
+
+    cat <<\EOF > ../noobs/flavours.json
+{
+  "flavours": [
+    {
+      "name": "Raspbian - Boot to Scratch",
+      "description": "A version of Raspbian that boots straight into Scratch"
+    },
+    {
+      "name": "Raspbian",
+      "description": "A Debian wheezy port, optimised for the Raspberry Pi"
+    }  
+  ]
+}
+EOF
+
+    cat <<\EOF > ../noobs/os.json
+{
+  "name": "Raspbian",
+  "version": "wheezy",
+  "release_date": "2013-09-10",
+  "kernel": "3.6",
+  "description": "A community-created port of Debian wheezy, optimised for the Raspberry Pi"
+}
+EOF
+
+    cat <<\EOF > ../noobs/release_notes.txt
+2013-09-10:
+  * Updated to current top of tree firmware
+  * Update squeak-vm, including fastblit optimised for the Raspbery Pi
+  * Include Sonic Pi and a fixed jackd2 package
+  * Support boot to Scratch
+  * Inherit keyboard and language settings from NOOBS
+EOF
+    wget http://asbradbury.org/tmp/raspi/marketing.tar -O ../noobs/marketing.tar
+  
+  fi
   sudo umount $BOOT_DEV
   sudo umount $ROOT_DEV
   detach_image_from_nbd /dev/nbd0
