various fixes to setup_spindle_environment
Using the $DEB_MIRROR from config doesn't work if you're building a raspbian
image (as that mirror only has armhf packages). Instead, always use
http.debian.net.

Makes a number of changes so that it can deal with the difference in schroot
1.4 as used in Ubuntu 10.04. Closes #115. Closes #130

diff --git a/setup_spindle_environment b/setup_spindle_environment
--- a/setup_spindle_environment
+++ b/setup_spindle_environment
@@ -28,7 +28,7 @@ TARGET_DIR=$(readlink -m "$1")
 
 . ./common
 
-ensure_installed schroot debootstrap
+ensure_installed schroot debootstrap debian-archive-keyring
 
 ask_yn y "About to set up chroot in '%s'. Ok?" "$TARGET_DIR" || die "You said no. Exiting"
 read_val USERS "${USERS-$SUDO_USER}" "What user should be able to schroot?"
@@ -56,7 +56,19 @@ printf "\nCreated %s:\n\n" "$SCHROOT_SPINDLE_CONF"
 cat "$SCHROOT_SPINDLE_CONF"
 printf "\n"
 
-[ ! -e $ETC_SCHROOT_SPINDLE ] && cp -a /etc/schroot/default $ETC_SCHROOT_SPINDLE
+if [ ! -e $ETC_SCHROOT_SPINDLE ]; then
+  if [ -e /etc/schroot/default ]; then
+    cp -a /etc/schroot/default $ETC_SCHROOT_SPINDLE
+  else
+    ## Should work for schroot 1.4 as in Ubuntu 10.04
+    mkdir $ETC_SCHROOT_SPINDLE
+    for FN in copyfiles mount nssdatabases; do
+      cp -a /etc/schroot/${FN}-defaults $ETC_SCHROOT_SPINDLE/$FN
+    done
+    mv $ETC_SCHROOT_SPINDLE/mount $ETC_SCHROOT_SPINDLE/fstab
+  fi
+fi
+
 cat << EOF > $ETC_SCHROOT_SPINDLE/config
 # Filesystems to mount inside the chroot.
 FSTAB="$ETC_SCHROOT_SPINDLE/fstab"
@@ -72,14 +84,17 @@ EOF
 # See http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=648459
 sed $ETC_SCHROOT_SPINDLE/fstab -e "s|^\(/home.*\),bind\(.*\)|\1,rbind\2|" > $ETC_SCHROOT_SPINDLE/fstab.new || true
 mv $ETC_SCHROOT_SPINDLE/fstab.new $ETC_SCHROOT_SPINDLE/fstab || true
-sed -i $ETC_SCHROOT_SPINDLE/nssdatabases -e "s/^passwd$/#passwd/"
-sed -i $ETC_SCHROOT_SPINDLE/nssdatabases -e "s/^shadow$/#shadow/"
-sed -i $ETC_SCHROOT_SPINDLE/nssdatabases -e "s/^group$/#group/"
+# Delete rather than comment out, as schroot 1.4 has no support for comments 
+# in nssdatabases
+sed -i $ETC_SCHROOT_SPINDLE/nssdatabases -e "/^passwd$/d"
+sed -i $ETC_SCHROOT_SPINDLE/nssdatabases -e "/^shadow$/d"
+sed -i $ETC_SCHROOT_SPINDLE/nssdatabases -e "/^group$/d"
 
 debootstrap \
   --include="qemu,bash-completion,augeas-tools,debootstrap,less,\
   sudo,parted,openssh-client,e2fsprogs,dosfstools,squashfs-tools,bzip2,git,zerofree" \
-  wheezy "$TARGET_DIR" "$DEB_MIRROR" || die "Debootstrap failed"
+  wheezy "$TARGET_DIR" http://http.debian.net/debian || die "Debootstrap failed"
+rm "$TARGET_DIR/dev/shm" # required on my 10.04 for schroot to work
 
 # Copy passwd/shadow/group databases
 getent passwd > "$TARGET_DIR/etc/passwd"
