wheezy-stage3: bugfixes, save space with hardlink and regen ssh host keys on boot

diff --git a/wheezy-stage3 b/wheezy-stage3
--- a/wheezy-stage3
+++ b/wheezy-stage3
@@ -135,13 +135,34 @@ EOF
 remove_ssh_host_keys() {
   ssh_in_to_qemu sh -x - <<EOF
 rm -f /mnt/etc/ssh/ssh_host_*_key*
+cat <<\RCL | tee /mnt/etc/rc.local
+#!/bin/sh -e
+#
+# rc.local
+#
+# This script is executed at the end of each multiuser runlevel.
+# Make sure that the script will "exit 0" on success or any other
+# value on error.
+#
+# In order to enable or disable this script just change the execution
+# bits.
+#
+# By default this script does nothing.
+
+# re-generate the ssh host keys if necessary
+if [ ! -e /etc/ssh/ssh_host_rsa_key ]; then
+  dpkg-reconfigure openssh-server
+fi
+
+exit 0
+RCL
 EOF
 }
 
 configure_ifplugd() {
   onvm_chroot sh -l -ex - <<\EOF
-sed /etc/default/ifplugd -e 's/^INTERFACES.*/INTERFACES="auto"/'
-sed /etc/default/ifplugd -e 's/^HOTPLUG_INTERFACES.*/HOTPLUG_INTERFACES="all"/'
+sed /etc/default/ifplugd -i -e 's/^INTERFACES.*/INTERFACES="auto"/'
+sed /etc/default/ifplugd -i -e 's/^HOTPLUG_INTERFACES.*/HOTPLUG_INTERFACES="all"/'
 EOF
 }
 
@@ -165,8 +186,15 @@ fiddle_default_PATH() {
   # This sed match is clearly brittle and specific to the current debian 
   # /etc/profile
   onvm_chroot sh -l -ex - <<EOF
-  sed /etc/profile -e \
+  sed /etc/profile -i -e \
   's|PATH="/usr/.*games.*$|PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games"|'
+EOF
+}
+
+save_space_using_hardlink() {
+  onvm_chroot sh -l -e - <<\EOF
+apt-get install hardlink
+hardlink -t /usr/share/doc
 EOF
 }
 
@@ -182,6 +210,7 @@ add_pi_user_to_groups || die "Failed to add pi user to standard groups"
 add_opt_vc_lib_to_ld_so || die "Problem adding /opt/vc/lib to /etc/ld.so.conf.d"
 setup_sudoers || die "problem setting up sudoers"
 fiddle_default_PATH || die "Problem fiddling default PATH"
+save_space_using_hardlink || die "Problem with hardlink"
 allow_starting_services
 remove_ssh_host_keys
 shutdown_qemu || die "Failed to shutdown qemu"
